### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by vkargov** [grtetrault/pcre2.py#5] opened 2024-02-19 00:30 UTC
Hi there,

I wanted to give this library a try, so I installed it, and noticed that if I run the following simple program, the memory consumed by the process increases rapidly. (The leak happens in other couple use cases I've tried as well).
I don't think it is supposed to happen? Am I doing something wrong?
It looks like memory is being leaked. If you open it in the top utility, you should see the %MEM go up until it eats up whole memory and dies to Linux's OOM killer.

```python3
import pcre2

re = pcre2.compile('ab|ba', 0, True)
while True:
    m = re.scan('abba babababa bbabaababab')
    del m
```

PCRE2.py version: 0.3.0 from Pip
libpcre2 version: 10.39-3ubuntu0.1

**Comment by vkargov** [comment] 2024-02-19 11:01
I ran the test program through Valgrind and it reported memory leaks commensurate with the one I'm observing. Will likely share more data if I don't forget.

**Comment by grtetrault** [comment] 2024-02-22 01:09
Hi @vkargov thanks for raising this, and I'm able to replicate on my end. It looks like the cause was not freeing the `Py_buffer` pointer itself after releasing the reference - missed that one! Working on a fix

**Comment by vkargov** [comment] 2024-02-22 17:58
Thanks for looking into it!
I'm pretty sure one of the leaks is due to memory allocation inside get_buffer()
I'm not very knowledgeable about Python's internals, but it seems like a more idiomatic way would be to allocate the buffer on stack (as opposed to the heap) and call get_buffer() with a pointer to it, like this:
```python
cdef Py_buffer buf
get_buffer(self._subject, &buf)
```
That should obviate the need for a `malloc()` and `free()` in `get_buffer()`.
However when I tried making that change, it looks like it fixed the example I have shown, but it would still cause leaks with in other use cases such as with string substitution (and possibly other actions, not sure) - which makes me think there may be more than one cause.

**Comment by grtetrault** [comment] 2024-02-25 19:57
I made some changes to more consistently free any allocated `Py_buffer` pointers, as well as some memory leaks in the `Scanner` classes `match_data`. Closing this issue as the above example is working as expected, but feel free to open another issue if you see another leak/similar bug - thanks!

**Closed by grtetrault** 2024-02-25 19:57 UTC

**Comment by vkargov** [comment] 2024-02-28 08:06
That's awesome! :fire:  I just gave the updated library a go and memory consumption seems much more reasonable. I'll let you know if I see something weird. Thanks for supporting your library. :relaxed:

**Comment by vkargov** [comment] 2024-03-17 00:24
Just wanted to give a follow up that I think I'm still seeing continuously increasing memory consumption that leads to OOM events. It doesn't happen with the standard regexp library, so I assume it's related to PCRE2.py. It also doesn't seem to be reported by Valgrind (not all of it at least?) which makes me think it could be something that still has an internal reference.

I didn't get to debug it so not sure when (and if) I would be able to file another issue with my setup, but I just wanted to give a heads up either way. If leak scenarios are tested and monitored more deeply in the future, I think it will ensure the library's success and wider adoption.

**Comment by grtetrault** [comment] 2024-03-20 22:43
Hi @vkargov thanks for the continued involvement on this - could you provide some code that your seeing the increasing memory usage on?

**Comment by vkargov** [comment] 2024-03-22 07:47
Sorry, no code! Would've opened a bug if I had a reliable way to reproduce.
To be clear: I understand this is not constructive and I definitely am not expecting any kind of fix. Just wanted to give a heads up before my ADHD brain moves on and gets obsessed with something completely different! 😅
